In [4]:
"""# Retail Sales Revenue Analysis

## Project Objective

The objective of this project is to analyze e-commerce sales data to identify revenue trends, customer behavior, and profitability drivers.

## Dataset

This dataset contains Brazilian e-commerce transactions including orders, customers, products, and payments.

## Analysis goals:

• Clean datasets  
• Perform exploratory analysis  
• Identify KPIs  
• Generate business insights  """

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

products = pd.read_csv("../data/raw/olist_products_dataset.csv")

payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

orders.head()

orders.info()

orders.describe()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [5]:
orders.info()

customers.info()

order_items.info()

products.info()

payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB
<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [6]:
##Data quality assessement

In [7]:
orders.isnull().sum()

customers.isnull().sum()

order_items.isnull().sum()

products.isnull().sum()

payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [8]:
orders.duplicated().sum()

customers.duplicated().sum()

order_items.duplicated().sum()

products.duplicated().sum()

payments.duplicated().sum()

np.int64(0)

In [9]:
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [10]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [11]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [12]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [13]:
products[
    products['product_category_name'].isnull()
].head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

In [ ]:
######Missing delivery dates correspond primarily to orders that were not delivered. These values were retained because they reflect the true business process rather than data errors.

In [14]:
orders['purchase_year'] = (
    orders['order_purchase_timestamp'].dt.year
)

orders['purchase_month'] = (
    orders['order_purchase_timestamp'].dt.month
)

orders['purchase_day'] = (
    orders['order_purchase_timestamp'].dt.day
)

In [16]:
print(orders.shape)
print(customers.shape)
print(order_items.shape)
print(products.shape)
print(payments.shape)

(99441, 11)
(99441, 5)
(112650, 7)
(32951, 9)
(103886, 5)

In [17]:
sales = orders.merge(
    customers,
    on='customer_id',
    how='left'
)

In [18]:
sales = sales.merge(
    order_items,
    on='order_id',
    how='left'
)

In [19]:
sales = sales.merge(
    products,
    on='product_id',
    how='left'
)

In [ ]:
#One order item purchased by one customer

In [20]:
total_revenue = sales['price'].sum()

total_orders = sales['order_id'].nunique()

total_customers = sales['customer_unique_id'].nunique()

aov = total_revenue / total_orders

In [21]:
sales.shape

(113425, 29)

In [ ]:
## Data Cleaning Decisions

### Missing Values

- Missing delivery dates were retained because they correspond to orders that were not completed or delivered.
- Missing product category information was retained for further investigation.

### Duplicates

- No fully duplicated rows were identified.

### Data Types

- Order date fields were converted from string format to datetime format.

### Feature Engineering

- Created purchase_year
- Created purchase_month
- Created purchase_day

In [22]:
sales['order_id'].nunique()

99441

In [23]:
sales['product_id'].isnull().sum()

np.int64(775)

In [24]:
total_revenue = sales['price'].sum()
total_revenue

np.float64(13591643.7)

In [25]:
total_orders = sales['order_id'].nunique()
total_orders

99441

In [26]:
total_customers = sales['customer_unique_id'].nunique()
total_customers

96096

In [27]:
aov = total_revenue / total_orders
aov

np.float64(136.68048088816482)

In [28]:
avg_items_per_order = (
    sales.shape[0] / total_orders
)
avg_items_per_order

1.1406260998984323

In [29]:
kpi_summary = pd.DataFrame({
    'KPI': [
        'Total Revenue',
        'Total Orders',
        'Unique Customers',
        'Average Order Value',
        'Average Items Per Order'
    ],
    'Value': [
        total_revenue,
        total_orders,
        total_customers,
        aov,
        avg_items_per_order
    ]
})

kpi_summary

                       KPI         Value
0            Total Revenue  1.359164e+07
1             Total Orders  9.944100e+04
2         Unique Customers  9.609600e+04
3      Average Order Value  1.366805e+02
4  Average Items Per Order  1.140626e+00

monthly revenue analysis